export const GET_ORDERS_REQUEST = 
"GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = 
"GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = 
"GET_ORDERS_FAIL" 

export const CREATE_ORDERS_REQUEST = 
"CREATE_ORDERS_REQUEST"
export const CREATE_ORDERS_SUCCESS = 
"CREATE_ORDERS_SUCCESS"
export const CREATE_ORDERS_FAIL = 
"CREATE_ORDERS_FAIL" 

export const GET_ORDER_DETAILS_REQUEST = 
"GET_ORDER_DETAILS_REQUEST"
export const GET_ORDERS_DETAILS_SUCCESS = 
"GET_ORDERS_DETAILS_SUCCESS"
export const GET_ORDERS_DETAILS_FAIL = 
"GET_ORDERS_DETAILS_FAIL" 

export const CREATE_ORDERS_DETAILS_REQUEST = 
"CREATE_ORDERS_DETAILS_REQUEST"
export const CREATE_ORDERS_DETAILS_SUCCESS = 
"CREATE_ORDERS_DETAILS_SUCCESS"
export const CREATE_ORDERS_DETAILS_FAIL = 
"CREATE_ORDERS_DETAILS_FAIL" 

export const GET_ORDER_REPORTS_REQUEST = 
"GET_ORDER_REPORTS_REQUEST"
export const GET_ORDERS_REPORTS_SUCCESS = 
"GET_ORDERS_REPORTS_SUCCESS"
export const GET_ORDERS_REPORTS_FAIL = 
"GET_ORDERS_REPORTS_FAIL" 

export const GET_ORDER_TOTALS_REQUEST = 
"GET_ORDER_TOTALS_REQUEST"
export const GET_ORDERS_TOTALS_SUCCESS = 
"GET_ORDERS_TOTALS_SUCCESS"
export const GET_ORDERS_TOTALS_FAIL = 
"GET_ORDERS_TOTALS_FAIL" 