export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL" 

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL" 

export const CREATE_USER_BY_PHONE_REQUEST = "CREATE_USER_BY_PHONE_REQUEST"
export const CREATE_USER_BY_PHONE_SUCCESS = "CREATE_USER_BY_PHONE_SUCCESS"
export const CREATE_USER_BY_PHONE_FAIL = "CREATE_USER_BY_PHONE_FAIL"

export const GET_USER_LOGS_REQUEST = "GET_USER_LOGS_REQUEST"
export const GET_USER_LOGS_SUCCESS = "GET_USER_LOGS_SUCCESS"
export const GET_USER_LOGS_FAIL = "GET_USER_LOGS_FAIL" 

export const CREATE_USER_LOGS_REQUEST = "CREATE_USER_LOGS_REQUEST"
export const CREATE_USER_LOGS_SUCCESS = "CREATE_USER_LOGS_SUCCESS"
export const CREATE_USER_LOGS_FAIL = "CREATE_USER_LOGS_FAIL" 
